csk/urls.py
from django.urls import path
from csk.views import *

app_name='dhoni'

urlpatterns=[
    path('dhoni/',dhoni,name='dhoni')
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb
from mi.views import *
from rcb.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path('csk/',include("csk.urls")),
    path("rohit/",rohit,name="rohit"),
    path("rcb/",include("rcb.urls"))
    
    
]

rcb/urls.py
from django.urls import path
from rcb.views import *

app_name='virat'

urlpatterns=[
    path('virat/',virat,name='virat')
]

csk/models.py
from django.db import models

# Create your models here.

mi/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,"dhoni.html")

mi/views.py
from django.shortcuts import render

# Create your views here.
def rohit(request):
    return render(request,"rohit.html")

rcb/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'virat.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-image: url(https://wallpapercave.com/wp/wp6391159.jpg)"; >
<center> 
        <h1 style="color: yellow;">this is my frist HTML page in csk</h1>
        <h1 style="color: yellow;">DHONI TO rohit</h1>
        <a href="{% url 'rohit' %}" style="color: yellow;">navigate from rohit</a><br>
        <a href="{% url 'virat:virat' %}" style="color: yellow;">navigat from virat</a>
    </center>
</body>
</html>

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style= "background-image: url(https://i.pinimg.com/originals/c7/8c/27/c78c27d7965d720a26d34883088e714a.jpg);">
    <center>
        <h1 style="color:blue">this ia second HTML page in mi</h1>
        <h1 style="color: blue;">Rohit TO Virat</h1>
        <a href="{% url 'virat:virat' %}" style="color: blue;">navigate from virat</a><br>
        <a href="{% url 'dhoni:dhoni'%}"style="color: blue;">navigate from dhoni</a>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-image: url(https://wallpapercave.com/dwp2x/wp3978069.jpg);">
    <center>
        <h1 style="color: red;">THIS IS A VIRAT HTML PAGES ------3</h1>
        <h1 style="color: red;">VIRAT TO DHONI</h1>
        <a href="{% url 'dhoni:dhoni' %}" style="color: red;"> navigate to  dhoni</a><br>
        <a href="{% url 'rohit' %}" style="color: red;">navigate from rohit</a>
    </center>
</body>
</html>